# Generated by Django 5.2.1 on 2025-05-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_review_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(default='I am a user of this app'),
            preserve_default=False,
        ),
    ]
